import 'package:meta/meta.dart';

import '../cycle/cycle.dart';
import '../cycle/cycle_derivation.dart';
import '../cycle/pregnancy_event.dart';
import '../date_math.dart';
import '../db/app_database.dart';
import '../prediction/date_range.dart';
import '../prediction/predictor.dart';

/// Fixed "not a medical device" text carried verbatim on every exported report
/// (`requirements.md` §6). Kept as a `const` so a content test can assert it is
/// present and so there is exactly one wording to review.
const String clinicalReportDisclaimer =
    'This report was generated by olf, a personal cycle-tracking app, from data '
    'the user chose to log. olf is not a medical device: this document is not a '
    'medical record, a diagnosis, or a substitute for clinical assessment. The '
    'figures are only as complete and accurate as the entries behind them and '
    'may contain gaps. Any prediction is a rough estimate from past cycles, not '
    'a clinical forecast.';

/// The humility caveat printed next to the cycle prediction. The prediction is
/// anchored on the last logged period and is **not** rolled forward when a
/// period is late (see [Predictor]); this spells that out for a clinician.
const String clinicalReportPredictionCaveat =
    'Estimated from the range and regularity of recently logged cycles. It is '
    'not advanced automatically once a period is overdue — a late estimate means '
    'the last cycle is still open, not that the estimate failed.';

/// One row of the report's cycle table — a single derived [Cycle] flattened to
/// the numbers a clinician reads.
@immutable
class ReportCycle {
  const ReportCycle({
    required this.start,
    required this.end,
    required this.lengthInDays,
    required this.periodLengthInDays,
    required this.isLikelyGap,
    required this.isPregnancyGap,
  });

  /// First day of the period that opened the cycle.
  final DateTime start;

  /// Last recorded day of that period, or `null` if none was logged.
  final DateTime? end;

  /// Start-to-start length, or `null` for the still-open current cycle.
  final int? lengthInDays;

  /// Days of bleeding (inclusive), or `null` if the period has no end date.
  final int? periodLengthInDays;

  /// The interval is long enough that a period was probably not logged in
  /// between — surfaced, not hidden, and left out of the summary figures.
  final bool isLikelyGap;

  /// The interval covers a recorded pregnancy loss or birth (p1.11).
  final bool isPregnancyGap;

  /// `true` when this row fed the summary statistics.
  bool get countsTowardStats =>
      lengthInDays != null && !isLikelyGap && !isPregnancyGap;
}

/// Summary statistics over the cycles inside the report's included range.
///
/// Every figure is nullable and is `null` when there is not enough history —
/// there is no 28-day fallback (matches [CycleStats]).
@immutable
class ReportSummary {
  const ReportSummary({
    required this.cycleCount,
    required this.meanCycleLength,
    required this.shortestCycleLength,
    required this.longestCycleLength,
    required this.periodCount,
    required this.meanPeriodLength,
    required this.shortestPeriodLength,
    required this.longestPeriodLength,
    required this.regularity,
    required this.hasLikelyGap,
  });

  static const ReportSummary empty = ReportSummary(
    cycleCount: 0,
    meanCycleLength: null,
    shortestCycleLength: null,
    longestCycleLength: null,
    periodCount: 0,
    meanPeriodLength: null,
    shortestPeriodLength: null,
    longestPeriodLength: null,
    regularity: CycleRegularity.notEnoughData,
    hasLikelyGap: false,
  );

  /// Completed, non-gap cycles the cycle-length figures are based on.
  final int cycleCount;
  final int? meanCycleLength;
  final int? shortestCycleLength;
  final int? longestCycleLength;

  /// Periods with a recorded end date the period-length figures are based on.
  final int periodCount;
  final int? meanPeriodLength;
  final int? shortestPeriodLength;
  final int? longestPeriodLength;

  final CycleRegularity regularity;

  /// A likely missed-entry gap sits in the history — the figures exclude it,
  /// but the reader should know it is there.
  final bool hasLikelyGap;

  /// Spread (max − min) of cycle length in days, or `null` with < 1 cycle.
  int? get cycleLengthVariability =>
      (shortestCycleLength == null || longestCycleLength == null)
      ? null
      : longestCycleLength! - shortestCycleLength!;

  bool get isEmpty => cycleCount == 0 && periodCount == 0;
}

/// How many days a named symptom was marked present inside the range.
@immutable
class SymptomFrequency {
  const SymptomFrequency({required this.name, required this.dayCount});

  final String name;
  final int dayCount;
}

/// One basal-temperature reading, for the report's chart.
@immutable
class TemperaturePoint {
  const TemperaturePoint({required this.date, required this.celsius});

  final DateTime date;
  final double celsius;
}

/// A recorded pregnancy loss or birth inside the range (p1.11).
@immutable
class ReportPregnancyEvent {
  const ReportPregnancyEvent({required this.date, required this.kind});

  final DateTime date;
  final PregnancyEndKind kind;
}

/// A doctor-ready snapshot of the user's cycle history — the pure value object
/// the `app` layer renders to a PDF (p6.5). No rendering, no Flutter, no
/// `DateTime.now()`: build it with [buildClinicalReport] and a supplied
/// `generatedOn`, and the same inputs always produce the same report.
@immutable
class ClinicalReport {
  const ClinicalReport({
    required this.generatedOn,
    required this.requestedRange,
    required this.includedRange,
    required this.retentionExcludedEarlierData,
    required this.cycles,
    required this.summary,
    required this.symptomFrequency,
    required this.temperatureSeries,
    required this.pregnancyEvents,
    required this.prediction,
    this.disclaimer = clinicalReportDisclaimer,
    this.predictionCaveat = clinicalReportPredictionCaveat,
  });

  /// The day the report was generated (date-only).
  final DateTime generatedOn;

  /// The span the user asked for.
  final DateRange requestedRange;

  /// The span actually covered — clamped to the retention window when that
  /// window starts later than [requestedRange]. Equal to [requestedRange] when
  /// nothing was trimmed.
  final DateRange includedRange;

  /// `true` when the retention window (p2.3) excluded the earlier part of
  /// [requestedRange]; the report states this so a reader is not misled by a
  /// short history.
  final bool retentionExcludedEarlierData;

  /// Cycle table, oldest first.
  final List<ReportCycle> cycles;

  final ReportSummary summary;

  /// Symptom-frequency table, most frequent first (ties broken by name).
  final List<SymptomFrequency> symptomFrequency;

  /// Temperature readings inside the range, oldest first.
  final List<TemperaturePoint> temperatureSeries;

  /// Pregnancy loss / birth markers inside the range, oldest first.
  final List<ReportPregnancyEvent> pregnancyEvents;

  /// The current forecast, or `null` when the history is too thin to say
  /// anything. When non-null, print it beside [predictionCaveat].
  final CyclePrediction? prediction;

  final String disclaimer;
  final String predictionCaveat;

  /// `true` when the report carries at least one cycle, symptom, temperature
  /// reading or pregnancy event — the UI preview uses this to enable "Generate".
  bool get hasAnyData =>
      cycles.isNotEmpty ||
      symptomFrequency.isNotEmpty ||
      temperatureSeries.isNotEmpty ||
      pregnancyEvents.isNotEmpty;
}

/// Build a [ClinicalReport] from the user's data and a requested date range.
///
/// Pure and deterministic: pass a fixed [generatedOn] and the same rows and the
/// output is identical. [retentionCutoff] is the oldest calendar day the user
/// still keeps (`RetentionWindow.cutoff`, p2.3), or `null` when auto-delete is
/// off — any data before it is excluded and, if it fell inside [rangeStart] …
/// [rangeEnd], [ClinicalReport.retentionExcludedEarlierData] is set.
///
/// [symptomNames] maps a `symptomTypeId` to its catalogue name (active **or**
/// archived); an id with no entry renders as "Removed symptom".
ClinicalReport buildClinicalReport({
  required DateTime generatedOn,
  required DateTime rangeStart,
  required DateTime rangeEnd,
  DateTime? retentionCutoff,
  required List<Period> periods,
  required List<PregnancyEvent> pregnancyEvents,
  required List<DailySymptomEntry> symptomEntries,
  required Map<int, String> symptomNames,
  required List<BbtEntry> temperatures,
  CyclePrediction? prediction,
}) {
  final reqStart = dateOnly(rangeStart);
  final reqEnd = dateOnly(rangeEnd);
  if (reqEnd.isBefore(reqStart)) {
    throw ArgumentError('rangeEnd ($reqEnd) is before rangeStart ($reqStart)');
  }

  final cutoff = retentionCutoff == null ? null : dateOnly(retentionCutoff);
  final incStart = (cutoff != null && cutoff.isAfter(reqStart))
      ? cutoff
      : reqStart;
  final retentionExcluded = incStart.isAfter(reqStart);

  bool inRange(DateTime d) {
    final day = dateOnly(d);
    return !day.isBefore(incStart) && !day.isAfter(reqEnd);
  }

  // Cycles: derive from the full period history so start-to-start lengths are
  // correct across the range boundary, then keep the ones that open inside it.
  final derived = deriveCycles(periods, pregnancyEvents: pregnancyEvents);
  final inWindow = derived.where((c) => inRange(c.periodStart)).toList();
  final cycles = <ReportCycle>[
    for (final c in inWindow.reversed) // deriveCycles is newest-first
      ReportCycle(
        start: c.periodStart,
        end: c.periodEnd,
        lengthInDays: c.lengthInDays,
        periodLengthInDays: c.periodLengthInDays,
        isLikelyGap: c.isLikelyGap,
        isPregnancyGap: c.isPregnancyGap,
      ),
  ];

  final summary = _summarise(inWindow);

  // Symptom frequency: one entry per (day, symptom), so a plain count by id is
  // the number of days that symptom was marked.
  final byId = <int, int>{};
  for (final e in symptomEntries) {
    if (!inRange(e.date)) continue;
    byId[e.symptomTypeId] = (byId[e.symptomTypeId] ?? 0) + 1;
  }
  final symptomFrequency =
      byId.entries
          .map(
            (e) => SymptomFrequency(
              name: symptomNames[e.key] ?? 'Removed symptom',
              dayCount: e.value,
            ),
          )
          .toList()
        ..sort((a, b) {
          final byCount = b.dayCount.compareTo(a.dayCount);
          return byCount != 0 ? byCount : a.name.compareTo(b.name);
        });

  final temperatureSeries =
      temperatures
          .where((t) => inRange(t.date))
          .map(
            (t) => TemperaturePoint(
              date: dateOnly(t.date),
              celsius: t.tempCelsius,
            ),
          )
          .toList()
        ..sort((a, b) => a.date.compareTo(b.date));

  final reportEvents =
      pregnancyEvents
          .where((e) => inRange(e.date))
          .map((e) => ReportPregnancyEvent(date: e.date, kind: e.kind))
          .toList()
        ..sort((a, b) => a.date.compareTo(b.date));

  return ClinicalReport(
    generatedOn: dateOnly(generatedOn),
    requestedRange: DateRange(reqStart, reqEnd),
    includedRange: DateRange(incStart, reqEnd),
    retentionExcludedEarlierData: retentionExcluded,
    cycles: cycles,
    summary: summary,
    symptomFrequency: symptomFrequency,
    temperatureSeries: temperatureSeries,
    pregnancyEvents: reportEvents,
    prediction: prediction,
  );
}

/// Summary figures over [inWindowNewestFirst] (the in-range cycles, as
/// `deriveCycles` orders them). Cycle-length figures use completed, non-gap
/// cycles; period-length figures use every cycle with a recorded period end.
ReportSummary _summarise(List<Cycle> inWindowNewestFirst) {
  if (inWindowNewestFirst.isEmpty) return ReportSummary.empty;

  final cycleLengths = <int>[
    for (final c in inWindowNewestFirst)
      if (c.lengthInDays != null && !c.isLikelyGap && !c.isPregnancyGap)
        c.lengthInDays!,
  ];
  final periodLengths = <int>[
    for (final c in inWindowNewestFirst)
      if (c.periodLengthInDays != null) c.periodLengthInDays!,
  ];

  // Regularity: reuse the app-wide classifier so the report agrees with the
  // rest of olf (it caps at the most recent `recentWindow` cycles and applies
  // its own gap handling).
  final regularity = CycleStats.from(inWindowNewestFirst).regularity;

  return ReportSummary(
    cycleCount: cycleLengths.length,
    meanCycleLength: _mean(cycleLengths),
    shortestCycleLength: _min(cycleLengths),
    longestCycleLength: _max(cycleLengths),
    periodCount: periodLengths.length,
    meanPeriodLength: _mean(periodLengths),
    shortestPeriodLength: _min(periodLengths),
    longestPeriodLength: _max(periodLengths),
    regularity: regularity,
    hasLikelyGap: inWindowNewestFirst.any((c) => c.isLikelyGap),
  );
}

int? _mean(List<int> xs) =>
    xs.isEmpty ? null : (xs.reduce((a, b) => a + b) / xs.length).round();
int? _min(List<int> xs) =>
    xs.isEmpty ? null : xs.reduce((a, b) => a < b ? a : b);
int? _max(List<int> xs) =>
    xs.isEmpty ? null : xs.reduce((a, b) => a > b ? a : b);
