import 'package:drift/native.dart';
import 'package:drift_dev/api/migrations_native.dart';
import 'package:olf_core/olf_core.dart';
import 'package:sqlite3/sqlite3.dart';
import 'package:test/test.dart';

import 'generated/schema.dart';

/// p5.6 — the migration matrix. For every historical schema version, a database
/// seeded at that version must upgrade to the current version (v10) with:
///   (a) the resulting schema matching the committed v10 snapshot exactly,
///   (b) `PRAGMA integrity_check` / `foreign_key_check` clean,
///   (c) every seeded row still present and byte-for-byte unchanged,
///   (d) tables added by later versions present and empty (except the v1→v2
///       `periodStart` carry-over and the `<4 → *` built-in symptom seed, the
///       only two data transforms in the whole history).
///
/// p6.1 — extended to v7: the `from` loops now reach v6, and the first
/// column-level migration (v6→v7 adds `source` + `external_id` to `bbt_entries`
/// and `daily_flows`) is asserted — every pre-v7 row must come out with
/// `source = 'manual'` and `external_id` NULL.
///
/// p7.5 — extended to v8: the `from` loops reach v7, and the additive v7→v8
/// migration (adds the `pain_entries` table) is asserted present-and-empty from
/// every pre-v8 database and usable through `DriftPainRepository`; the backup
/// round-trip carries a real pain row across the migration.
///
/// p7.6 — extended to v9: the `from` loops reach v8, and the additive v8→v9
/// migration (adds the `pmdd_ratings` table) is asserted present-and-empty from
/// every pre-v9 database and usable through `DriftPmddRatingRepository` (an
/// explicit `none` rating included); the backup round-trip carries real PMDD
/// rows across the migration.
///
/// p8.1a — extended to v10: the `from` loops reach v9, and the second
/// column-level migration (v9→v10 adds `measurement_kind` to `bbt_entries`) is
/// asserted — every pre-v10 `bbt_entries` row must come out `'basal'`. The
/// backup round-trip carries a real `sleepingWrist` row across the migration.
///
/// p8.2 — extended to v11: the `from` loops reach v10, and the third
/// column-level migration (v10→v11 adds `source_device` to **both**
/// `daily_flows` and `bbt_entries`) is asserted — every pre-v11 row in either
/// table must come out with `source_device` NULL. The backup round-trip carries
/// a real device-tagged flow row and BBT row across the migration.
///
/// Schema snapshots live in `core/drift_schemas/` (regenerated by
/// `dart run tool/dump_historical_schemas.dart`); the `generated/` helpers by
/// `dart run drift_dev schema generate drift_schemas/ test/db/generated/`.
void main() {
  late SchemaVerifier verifier;

  setUpAll(() => verifier = SchemaVerifier(GeneratedHelper()));

  int secs(DateTime d) => d.millisecondsSinceEpoch ~/ 1000;

  // Deliberately awkward seed values: an epoch-adjacent date, a far-future
  // date, NULLs in every nullable column, and notes with combining marks /
  // RTL / CJK / emoji.
  final earlyDate = DateTime.utc(1971, 2, 3);
  final farFuture = DateTime.utc(2099, 12, 31);
  const weirdNote = 'Krä́mpfe — 日本語 · اختبار · 🩸\x00trailing';
  const weirdNoteNoNul = 'Krä́mpfe — 日本語 · اختبار · 🩸';

  /// Insert representative rows into every table that exists at [from].
  /// Returns the user-added symptom id (or `null` when [from] < 4).
  int? seedAt(Database raw, int from) {
    // cycle_events (v1): two point events, incl. a v1-style periodStart that the
    // v1→v2 migration must carry into `periods`.
    raw.execute(
      'INSERT INTO cycle_events (type, date, created_at) VALUES (?, ?, ?)',
      ['periodStart', secs(earlyDate), secs(earlyDate)],
    );
    raw.execute(
      'INSERT INTO cycle_events (type, date, created_at) VALUES (?, ?, ?)',
      [
        'birth',
        secs(DateTime.utc(2026, 6, 15)),
        secs(DateTime.utc(2026, 6, 15)),
      ],
    );

    if (from >= 2) {
      // one closed period, one open (end NULL).
      raw.execute(
        'INSERT INTO periods (start_date, end_date, created_at, updated_at) '
        'VALUES (?, ?, ?, ?)',
        [secs(DateTime.utc(2026, 1, 1)), secs(DateTime.utc(2026, 1, 5)), 0, 0],
      );
      raw.execute(
        'INSERT INTO periods (start_date, end_date, created_at, updated_at) '
        'VALUES (?, ?, ?, ?)',
        [secs(farFuture), null, 0, 0],
      );
    }

    if (from >= 3) {
      raw.execute(
        'INSERT INTO daily_flows (date, intensity, clot_size, created_at, updated_at) '
        'VALUES (?, ?, ?, ?, ?)',
        [secs(DateTime.utc(2026, 1, 2)), 'heavy', 'large', 0, 0],
      );
      raw.execute(
        'INSERT INTO daily_flows (date, intensity, clot_size, created_at, updated_at) '
        'VALUES (?, ?, ?, ?, ?)',
        [secs(DateTime.utc(2026, 1, 3)), 'spotting', null, 0, 0],
      );
    }

    int? userSymptomId;
    if (from >= 4) {
      // A realistic v4+ database already holds the 11 built-ins (seeded when the
      // real app first reached v4); the synthetic `schemaAt` does not add them,
      // so seed them here, then a user-added symptom on top.
      for (var i = 0; i < kBuiltInSymptomNames.length; i++) {
        raw.execute(
          'INSERT INTO symptom_types (name, sort_order, is_built_in, created_at, updated_at) '
          'VALUES (?, ?, 1, 0, 0)',
          [kBuiltInSymptomNames[i], i],
        );
      }
      raw.execute(
        'INSERT INTO symptom_types (name, sort_order, is_built_in, archived_at, created_at, updated_at) '
        'VALUES (?, ?, 0, ?, 0, 0)',
        [weirdNoteNoNul, 99, secs(DateTime.utc(2026, 5, 1))],
      );
      userSymptomId = raw.lastInsertRowId;
      raw.execute(
        'INSERT INTO daily_symptom_entries (date, symptom_type_id, created_at) '
        'VALUES (?, ?, ?)',
        [secs(DateTime.utc(2026, 1, 2)), userSymptomId, 0],
      );
    }

    if (from >= 5) {
      raw.execute(
        'INSERT INTO bbt_entries (date, temp_celsius, created_at, updated_at) '
        'VALUES (?, ?, ?, ?)',
        [secs(DateTime.utc(2026, 1, 2)), 36.615, 0, 0],
      );
      raw.execute(
        'INSERT INTO cervical_mucus_entries (date, type, created_at, updated_at) '
        'VALUES (?, ?, ?, ?)',
        [secs(DateTime.utc(2026, 1, 2)), 'eggWhite', 0, 0],
      );
      raw.execute(
        'INSERT INTO app_settings (key, value, updated_at) VALUES (?, ?, ?)',
        ['temperature_unit', 'fahrenheit', 0],
      );
      raw.execute(
        'INSERT INTO app_settings (key, value, updated_at) VALUES (?, ?, ?)',
        ['weird_note', weirdNote, 0],
      );
    }

    if (from >= 6) {
      // v6 tables — seeded so the v6 → v7 column-add step carries real data.
      raw.execute(
        'INSERT INTO medications (name, dosage, notes, created_at, updated_at) '
        'VALUES (?, ?, ?, 0, 0)',
        ['Iron', '50 mg', weirdNoteNoNul],
      );
      raw.execute(
        'INSERT INTO birth_control_entries (method, started_on, ended_on, created_at, updated_at) '
        'VALUES (?, ?, ?, 0, 0)',
        ['pill', secs(DateTime.utc(2026, 1, 1)), null],
      );
      raw.execute(
        'INSERT INTO reminders (kind, hour, minute, enabled, created_at, updated_at) '
        'VALUES (?, ?, ?, 1, 0, 0)',
        ['medication', 9, 30],
      );
    }

    return userSymptomId;
  }

  Future<void> expectIntegrity(AppDatabase db) async {
    final integrity = await db
        .customSelect('PRAGMA integrity_check')
        .getSingle();
    expect(integrity.data.values.first, 'ok');
    final fkErrors = await db.customSelect('PRAGMA foreign_key_check').get();
    expect(fkErrors, isEmpty);
    final version = await db.customSelect('PRAGMA user_version').getSingle();
    expect(version.data.values.first, 11);
  }

  Future<List<Map<String, Object?>>> rows(AppDatabase db, String table) async =>
      (await db.customSelect('SELECT * FROM "$table" ORDER BY rowid').get())
          .map((r) => r.data)
          .toList();

  for (final from in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) {
    test(
      'v$from database upgrades to v11, schema matches, every row intact',
      () async {
        final schema = await verifier.schemaAt(from);
        final userSymptomId = seedAt(schema.rawDatabase, from);

        final db = AppDatabase(schema.newConnection());
        addTearDown(db.close);

        // Runs the real `onUpgrade` and asserts the resulting schema equals the
        // committed v11 snapshot (throws SchemaMismatch otherwise).
        await verifier.migrateAndValidate(db, 11);
        await expectIntegrity(db);

        // cycle_events: untouched by every migration.
        final events = await rows(db, 'cycle_events');
        expect(events, hasLength(2));
        expect(events[0]['type'], 'periodStart');
        expect(events[0]['date'], secs(earlyDate));
        expect(events[1]['type'], 'birth');

        // periods.
        final periods = await rows(db, 'periods');
        if (from == 1) {
          // v1→v2 carry-over: the periodStart event became one open-ended period.
          expect(periods, hasLength(1));
          expect(periods.single['start_date'], secs(earlyDate));
          expect(periods.single['end_date'], isNull);
        } else {
          expect(periods, hasLength(2));
          expect(periods[0]['end_date'], secs(DateTime.utc(2026, 1, 5)));
          expect(periods[1]['start_date'], secs(farFuture));
          expect(periods[1]['end_date'], isNull);
        }

        // daily_flows.
        final flows = await rows(db, 'daily_flows');
        if (from <= 2) {
          expect(flows, isEmpty);
        } else {
          expect(flows, hasLength(2));
          expect(flows[0]['intensity'], 'heavy');
          expect(flows[0]['clot_size'], 'large');
          expect(flows[1]['intensity'], 'spotting');
          expect(flows[1]['clot_size'], isNull);
          // v7 (p6.1): every pre-v7 row is marked user-entered, no external id.
          // v11 (p8.2): and carries no device tag.
          for (final f in flows) {
            expect(f['source'], 'manual');
            expect(f['external_id'], isNull);
            expect(f['source_device'], isNull);
          }
        }

        // symptom_types.
        final symptoms = await rows(db, 'symptom_types');
        if (from <= 3) {
          // the `from < 4` migration seeds the 11 built-ins, nothing else.
          expect(symptoms.map((r) => r['name']), kBuiltInSymptomNames);
          expect(symptoms.every((r) => r['is_built_in'] == 1), isTrue);
        } else {
          expect(symptoms, hasLength(kBuiltInSymptomNames.length + 1));
          final user = symptoms.firstWhere((r) => r['id'] == userSymptomId);
          expect(user['name'], weirdNoteNoNul);
          expect(user['is_built_in'], 0);
          expect(user['archived_at'], secs(DateTime.utc(2026, 5, 1)));

          final entries = await rows(db, 'daily_symptom_entries');
          expect(entries.single['symptom_type_id'], userSymptomId);
          expect(entries.single['date'], secs(DateTime.utc(2026, 1, 2)));
        }

        // v5 tables.
        if (from <= 4) {
          expect(await rows(db, 'bbt_entries'), isEmpty);
          expect(await rows(db, 'cervical_mucus_entries'), isEmpty);
          expect(await rows(db, 'app_settings'), isEmpty);
        } else {
          final bbt = await rows(db, 'bbt_entries');
          expect(bbt.single['temp_celsius'], 36.615);
          // v7 (p6.1): the BBT row keeps its user-entered provenance.
          expect(bbt.single['source'], 'manual');
          expect(bbt.single['external_id'], isNull);
          // v10 (p8.1a): every pre-v10 BBT row is a basal body temperature.
          expect(bbt.single['measurement_kind'], 'basal');
          // v11 (p8.2): and carries no device tag.
          expect(bbt.single['source_device'], isNull);
          expect(
            (await rows(db, 'cervical_mucus_entries')).single['type'],
            'eggWhite',
          );
          final settings = {
            for (final r in await rows(db, 'app_settings'))
              r['key'] as String: r['value'],
          };
          expect(settings['temperature_unit'], 'fahrenheit');
          expect(settings['weird_note'], weirdNote);
        }

        // v6 tables: empty from a pre-v6 database, carried through when seeded
        // at v6.
        if (from <= 5) {
          expect(await rows(db, 'medications'), isEmpty);
          expect(await rows(db, 'birth_control_entries'), isEmpty);
          expect(await rows(db, 'reminders'), isEmpty);
        } else {
          expect((await rows(db, 'medications')).single['name'], 'Iron');
          expect(
            (await rows(db, 'birth_control_entries')).single['method'],
            'pill',
          );
          expect((await rows(db, 'reminders')).single['kind'], 'medication');
        }

        // v8 (p7.5): pain_entries is added by the v7→v8 step. No `from` in this
        // matrix predates it, so it is always present-and-empty here.
        expect(await rows(db, 'pain_entries'), isEmpty);

        // v9 (p7.6): pmdd_ratings is added by the v8→v9 step. `seedAt` never
        // touches it, so it is always present-and-empty from every version here.
        expect(await rows(db, 'pmdd_ratings'), isEmpty);

        // The migrated database is fully usable through the real repositories.
        await DriftMedicationRepository(
          db,
          now: () => DateTime(2026, 7, 1),
        ).add('Magnesium', dosage: '200 mg');
        expect(
          (await DriftMedicationRepository(
            db,
          ).activeMedications()).map((m) => m.name),
          contains('Magnesium'),
        );

        // …including the new v8 table.
        final pain = DriftPainRepository(db, now: () => DateTime(2026, 7, 1));
        await pain.setPain(
          DateTime(2026, 6, 20),
          intensity: SymptomSeverity.moderate,
          region: PainRegion.pelvic,
          note: weirdNoteNoNul,
          isFlare: true,
        );
        final row = (await pain.allEntries()).single;
        expect(row.intensity, SymptomSeverity.moderate);
        expect(row.region, PainRegion.pelvic);
        expect(row.note, weirdNoteNoNul);
        expect(row.isFlare, isTrue);

        // …and the new v9 table, including an explicit `none` rating
        // ("rated, nothing today") which this table stores as a real row.
        final pmdd = DriftPmddRatingRepository(
          db,
          now: () => DateTime(2026, 7, 1),
        );
        await pmdd.rateDay(DateTime(2026, 6, 21), {
          PmddSymptom.irritability: SymptomSeverity.severe,
          PmddSymptom.lowMood: SymptomSeverity.moderate,
          PmddSymptom.bloating: SymptomSeverity.none,
        });
        final ratings = await pmdd.ratingsOn(DateTime(2026, 6, 21));
        expect(ratings[PmddSymptom.irritability], SymptomSeverity.severe);
        expect(ratings[PmddSymptom.lowMood], SymptomSeverity.moderate);
        expect(ratings[PmddSymptom.bloating], SymptomSeverity.none);

        // …and the v10 `bbt_entries.measurement_kind` column: a passive Apple
        // Watch wrist reading round-trips through the real repository on the
        // migrated database, distinct from a typed basal one.
        final bbtRepo = DriftBbtRepository(db, now: () => DateTime(2026, 7, 1));
        await bbtRepo.setTemp(
          DateTime(2026, 6, 22),
          36.9,
          source: HealthDataSource.appleHealth,
          externalId: 'wrist-xyz',
          measurementKind: BbtMeasurementKind.sleepingWrist,
        );
        final wrist = await bbtRepo.tempOn(DateTime(2026, 6, 22));
        expect(wrist!.measurementKind, BbtMeasurementKind.sleepingWrist);
        expect(wrist.source, 'appleHealth');

        // …and the v11 `source_device` column on both per-day tables: an import
        // stamps the originating device, and correcting the row in-app clears
        // it (mirrors `source` → `manual`).
        await bbtRepo.setTemp(
          DateTime(2026, 6, 24),
          36.7,
          source: HealthDataSource.appleHealth,
          externalId: 'oura-bbt',
          sourceDevice: 'Oura',
        );
        expect(
          (await bbtRepo.tempOn(DateTime(2026, 6, 24)))!.sourceDevice,
          'Oura',
        );
        await bbtRepo.setTemp(DateTime(2026, 6, 24), 36.7);
        expect(
          (await bbtRepo.tempOn(DateTime(2026, 6, 24)))!.sourceDevice,
          isNull,
        );

        final flowRepo = DriftDailyFlowRepository(
          db,
          now: () => DateTime(2026, 7, 1),
        );
        await flowRepo.setFlow(
          DateTime(2026, 6, 24),
          intensity: FlowIntensity.medium,
          source: HealthDataSource.healthConnect,
          externalId: 'oura-flow',
          sourceDevice: 'com.ouraring.oura',
        );
        expect(
          (await flowRepo.flowOn(DateTime(2026, 6, 24)))!.sourceDevice,
          'com.ouraring.oura',
        );
        await flowRepo.setFlow(
          DateTime(2026, 6, 24),
          intensity: FlowIntensity.medium,
        );
        expect(
          (await flowRepo.flowOn(DateTime(2026, 6, 24)))!.sourceDevice,
          isNull,
        );
      },
    );
  }

  // Every single step v(N) → v(N+1) validates against that version's snapshot,
  // so a future bad step is caught in isolation.
  //
  // v2→v3 and v4→v5 are deliberately omitted. `onUpgrade` is not version-frozen
  // — `m.createTable` always builds a table in its *current* shape — so an
  // intermediate step that (re)creates `daily_flows` (introduced v3) or
  // `bbt_entries` (introduced v5) hands it the v7 provenance columns before the
  // target snapshot "should" carry them. Production never migrates to an
  // intermediate version (`to` is always the current `schemaVersion`); the
  // v2→v7 and v4→v7 paths are still checked strictly by the first loop above.
  // v7→v8 is safe to check in isolation: `pain_entries` only exists from v8, so
  // no intermediate `createTable` can hand it the wrong shape. v8→v9 is safe for
  // the same reason: `pmdd_ratings` only exists from v9. v9→v10 is safe because
  // the step's single `from` is v9 (≥ 5), so the `measurement_kind` add always
  // fires and the result matches the v10 snapshot — no intermediate `from`.
  // v10→v11 is safe for the same reason: the step's single `from` is v10 (≥ 5
  // and ≥ 3), so both `source_device` adds fire and the result matches the v11
  // snapshot.
  for (final from in [1, 3, 5, 6, 7, 8, 9, 10]) {
    final to = from + 1;
    test('single step v$from → v$to matches the v$to snapshot', () async {
      final schema = await verifier.schemaAt(from);
      final db = AppDatabase(schema.newConnection());
      addTearDown(db.close);
      await verifier.migrateAndValidate(db, to);
    });
  }

  // The end-to-end "OS update → migrate → restore a backup" path (ties in
  // p1.10): a database seeded at an old version is migrated to v10, backed up
  // via BackupService, then restored into a fresh v10 database — every table
  // must come back byte-for-byte. (`BackupService.import` only accepts a
  // same-schema document, so the backup is necessarily taken *after* the
  // migration; that is exactly the real recovery flow.)
  for (final from in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) {
    test(
      'v$from → migrate → backup → restore into a fresh v11 db round-trips',
      () async {
        final schema = await verifier.schemaAt(from);
        seedAt(schema.rawDatabase, from);

        final migrated = AppDatabase(schema.newConnection());
        addTearDown(migrated.close);
        await verifier.migrateAndValidate(migrated, 11);

        // A real pain row (v8) so the round-trip exercises `pain_entries` with
        // data, not just an empty table — note carries combining marks / RTL /
        // CJK / emoji, like the other weird-text seeds.
        await DriftPainRepository(
          migrated,
          now: () => DateTime(2026, 7, 1),
        ).setPain(
          DateTime(2026, 6, 20),
          intensity: SymptomSeverity.severe,
          region: PainRegion.lowerBack,
          note: weirdNoteNoNul,
          isFlare: true,
        );

        // Real PMDD rows (v9) too, including an explicit `none` — so the
        // round-trip exercises `pmdd_ratings` with data across the migration.
        await DriftPmddRatingRepository(
          migrated,
          now: () => DateTime(2026, 7, 1),
        ).rateDay(DateTime(2026, 6, 21), {
          PmddSymptom.irritability: SymptomSeverity.severe,
          PmddSymptom.lowMood: SymptomSeverity.moderate,
          PmddSymptom.bloating: SymptomSeverity.none,
        });

        // A real passive Apple Watch wrist reading (v10) so the round-trip
        // carries a `sleepingWrist` `bbt_entries` row — not just the `'basal'`
        // default — across the migration and back. It also carries a non-null
        // `source_device` (v11), so the round-trip exercises the new column on
        // `bbt_entries` with data.
        await DriftBbtRepository(
          migrated,
          now: () => DateTime(2026, 7, 1),
        ).setTemp(
          DateTime(2026, 6, 23),
          36.85,
          source: HealthDataSource.appleHealth,
          externalId: 'wrist-roundtrip',
          measurementKind: BbtMeasurementKind.sleepingWrist,
          sourceDevice: 'Oura',
        );

        // A device-tagged flow row (v11) so the round-trip carries the new
        // `daily_flows.source_device` column with data too.
        await DriftDailyFlowRepository(
          migrated,
          now: () => DateTime(2026, 7, 1),
        ).setFlow(
          DateTime(2026, 6, 24),
          intensity: FlowIntensity.light,
          source: HealthDataSource.healthConnect,
          externalId: 'flow-roundtrip',
          sourceDevice: 'com.ouraring.oura',
        );

        final backup = await BackupService(migrated).export();
        expect(backup.appSchemaVersion, 11);

        final restored = AppDatabase(NativeDatabase.memory());
        addTearDown(restored.close);
        await BackupService(restored).import(backup);

        final reExported = await BackupService(restored).export();
        for (final table in BackupService.tableOrder) {
          expect(
            reExported.tables[table],
            backup.tables[table],
            reason:
                'table "$table" differs after migrate+backup+restore from v$from',
          );
        }
      },
    );
  }
}
